namespace: "softasap"
name: "prometheus_box"
description: wraps sa_prometheus and sa_prometheus_alertmanager roles in one setup
version: 0.1.0
readme: "Readme.md"
authors:
    - "Vyacheslav Voronenko"
dependencies:
license:
    - "MIT"
tags:
    - softasap
repository: "https://github.com/oops-to-devops/prometheus_box"
documentation: "https://github.com/oops-to-devops/prometheus_box/blob/master/README.md"
homepage: "https://www.softasap.com"
issues: "https://github.com/orgs/oops-to-devops/projects/1"
